/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class AllocationsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:5001";
    }

    getFundStructure(): Promise<FundStructure> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/fundStructure";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetFundStructure(_response);
        });
    }

    protected processGetFundStructure(response: Response): Promise<FundStructure> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <FundStructure>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FundStructure>(<any>null);
    }

    getLookupAllocationTypes(): Promise<NamedLookupRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/allocationTypes";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupAllocationTypes(_response);
        });
    }

    protected processGetLookupAllocationTypes(response: Response): Promise<NamedLookupRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <NamedLookupRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NamedLookupRes[]>(<any>null);
    }

    getLookupDonationItems(): Promise<DonationItemRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/donationItems";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupDonationItems(_response);
        });
    }

    protected processGetLookupDonationItems(response: Response): Promise<DonationItemRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <DonationItemRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DonationItemRes[]>(<any>null);
    }

    getLookupDonationTypes(): Promise<NamedLookupRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/donationTypes";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupDonationTypes(_response);
        });
    }

    protected processGetLookupDonationTypes(response: Response): Promise<NamedLookupRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <NamedLookupRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NamedLookupRes[]>(<any>null);
    }

    getLookupFundDimension1Options(): Promise<FundDimensionOptionRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/fundDimension1Options";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupFundDimension1Options(_response);
        });
    }

    protected processGetLookupFundDimension1Options(response: Response): Promise<FundDimensionOptionRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <FundDimensionOptionRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FundDimensionOptionRes[]>(<any>null);
    }

    getLookupFundDimension2Options(): Promise<FundDimensionOptionRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/fundDimension2Options";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupFundDimension2Options(_response);
        });
    }

    protected processGetLookupFundDimension2Options(response: Response): Promise<FundDimensionOptionRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <FundDimensionOptionRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FundDimensionOptionRes[]>(<any>null);
    }

    getLookupFundDimension3Options(): Promise<FundDimensionOptionRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/fundDimension3Options";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupFundDimension3Options(_response);
        });
    }

    protected processGetLookupFundDimension3Options(response: Response): Promise<FundDimensionOptionRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <FundDimensionOptionRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FundDimensionOptionRes[]>(<any>null);
    }

    getLookupFundDimension4Options(): Promise<FundDimensionOptionRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/fundDimension4Options";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupFundDimension4Options(_response);
        });
    }

    protected processGetLookupFundDimension4Options(response: Response): Promise<FundDimensionOptionRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <FundDimensionOptionRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FundDimensionOptionRes[]>(<any>null);
    }

    getLookupSponsorshipSchemes(): Promise<NamedLookupRes[]> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/sponsorshipSchemes";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLookupSponsorshipSchemes(_response);
        });
    }

    protected processGetLookupSponsorshipSchemes(response: Response): Promise<NamedLookupRes[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <NamedLookupRes[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NamedLookupRes[]>(<any>null);
    }

    getAllLookups(criteria: LookupsCriteria): Promise<AllocationsLookupsRes> {
        let url_ = this.baseUrl + "/umbraco/api/Allocations/lookups/all";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(criteria);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllLookups(_response);
        });
    }

    protected processGetAllLookups(response: Response): Promise<AllocationsLookupsRes> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <AllocationsLookupsRes>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AllocationsLookupsRes>(<any>null);
    }
}

export interface Value {
}

export interface FundStructure extends Value {
    dimension1?: Dimension1 | undefined;
    dimension2?: Dimension2 | undefined;
    dimension3?: Dimension3 | undefined;
    dimension4?: Dimension4 | undefined;
}

export interface UmbracoContentOfFundDimension1Option extends Value {
    content?: IPublishedContent | undefined;
}

export interface IPublishedContent {
    id?: number;
    name?: string | undefined;
    urlSegment?: string | undefined;
    sortOrder?: number;
    level?: number;
    path?: string | undefined;
    templateId?: number | undefined;
    creatorId?: number;
    createDate?: Date;
    writerId?: number;
    updateDate?: Date;
    cultures?: { [key: string]: PublishedCultureInfo; } | undefined;
    itemType?: PublishedItemType;
    parent?: IPublishedContent | undefined;
    children?: IPublishedContent[] | undefined;
    childrenForAllCultures?: IPublishedContent[] | undefined;
}

export interface PublishedCultureInfo {
    culture?: string | undefined;
    name?: string | undefined;
    urlSegment?: string | undefined;
    date?: Date;
}

export enum PublishedItemType {
    Unknown = 0,
    Element = 1,
    Content = 2,
    Media = 3,
    Member = 4,
}

export interface UmbracoContentOfFundDimension1 extends Value {
    content?: IPublishedContent | undefined;
}

export interface UmbracoContentOfFundDimension2Option extends Value {
    content?: IPublishedContent | undefined;
}

export interface UmbracoContentOfFundDimension2 extends Value {
    content?: IPublishedContent | undefined;
}

export interface UmbracoContentOfFundDimension3Option extends Value {
    content?: IPublishedContent | undefined;
}

export interface UmbracoContentOfFundDimension3 extends Value {
    content?: IPublishedContent | undefined;
}

export interface UmbracoContentOfFundDimension4Option extends Value {
    content?: IPublishedContent | undefined;
}

export interface UmbracoContentOfFundDimension4 extends Value {
    content?: IPublishedContent | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}

export interface LookupRes {
    id?: string | undefined;
}

export interface NamedLookupRes extends LookupRes {
    name?: string | undefined;
}

export interface DonationItemRes extends NamedLookupRes {
    allowSingleDonations?: boolean;
    allowRegularDonations?: boolean;
    free?: boolean;
    price?: MoneyRes | undefined;
    dimension1Options?: FundDimensionOptionRes[] | undefined;
    dimension2Options?: FundDimensionOptionRes[] | undefined;
    dimension3Options?: FundDimensionOptionRes[] | undefined;
    dimension4Options?: FundDimensionOptionRes[] | undefined;
}

export interface MoneyRes {
    amount?: number;
    currency?: Currency | undefined;
    text?: string | undefined;
}

export interface UmbracoContentOfCurrency extends Value {
    content?: IPublishedContent | undefined;
}

export interface FundDimensionOptionRes extends NamedLookupRes {
    isUnrestricted?: boolean;
}

export interface LookupsRes {
}

export interface AllocationsLookupsRes extends LookupsRes {
    allocationTypes?: NamedLookupRes[] | undefined;
    donationItems?: DonationItemRes[] | undefined;
    donationTypes?: NamedLookupRes[] | undefined;
    fundDimension1Options?: FundDimensionOptionRes[] | undefined;
    fundDimension2Options?: FundDimensionOptionRes[] | undefined;
    fundDimension3Options?: FundDimensionOptionRes[] | undefined;
    fundDimension4Options?: FundDimensionOptionRes[] | undefined;
    sponsorshipSchemes?: NamedLookupRes[] | undefined;
}

export interface LookupsCriteria {
    types?: Types[] | undefined;
}

export interface Anonymous7 extends UmbracoContentOfFundDimension1 {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous extends Anonymous7 {
    isActive?: boolean;
    options?: Options[] | undefined;
}

export interface Dimension1 extends Anonymous {
}

export interface Anonymous8 extends UmbracoContentOfFundDimension2 {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous2 extends Anonymous8 {
    isActive?: boolean;
    options?: Options2[] | undefined;
}

export interface Dimension2 extends Anonymous2 {
}

export interface Anonymous9 extends UmbracoContentOfFundDimension3 {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous3 extends Anonymous9 {
    isActive?: boolean;
    options?: Options3[] | undefined;
}

export interface Dimension3 extends Anonymous3 {
}

export interface Anonymous10 extends UmbracoContentOfFundDimension4 {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous4 extends Anonymous10 {
    isActive?: boolean;
    options?: Options4[] | undefined;
}

export interface Dimension4 extends Anonymous4 {
}

export interface Anonymous5 extends UmbracoContentOfCurrency {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Currency extends Anonymous5 {
    symbol?: string | undefined;
    isBaseCurrency?: boolean;
    decimalDigits?: number;
}

export interface Anonymous6 extends Value {
    id?: string | undefined;
}

export interface Types extends Anonymous6 {
    lookupType?: string | undefined;
}

export interface Anonymous15 extends UmbracoContentOfFundDimension1Option {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous11 extends Anonymous15 {
    isUnrestricted?: boolean;
}

export interface Options extends Anonymous11 {
}

export interface Anonymous16 extends UmbracoContentOfFundDimension2Option {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous12 extends Anonymous16 {
    isUnrestricted?: boolean;
}

export interface Options2 extends Anonymous12 {
}

export interface Anonymous17 extends UmbracoContentOfFundDimension3Option {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous13 extends Anonymous17 {
    isUnrestricted?: boolean;
}

export interface Options3 extends Anonymous13 {
}

export interface Anonymous18 extends UmbracoContentOfFundDimension4Option {
    id?: string | undefined;
    name?: string | undefined;
}

export interface Anonymous14 extends Anonymous18 {
    isUnrestricted?: boolean;
}

export interface Options4 extends Anonymous14 {
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}