<Project>
    <PropertyGroup>
        <DefaultItemExcludes>$(DefaultItemExcludes);**\node_modules\**;**\dist\**</DefaultItemExcludes>
    </PropertyGroup>

    <PropertyGroup Condition="Exists('$(MSBuildProjectDirectory)\frontend')">
        <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
        <DefaultItemExcludes>$(DefaultItemExcludes);frontend\**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)\frontend')">
        <None Include="frontend\**" Exclude="frontend\**\dist\**;frontend\**\.turbo\**" />
    </ItemGroup>
</Project>
