using N3O.Umbraco.Localization;

namespace N3O.Umbraco.Crowdfunding;

public class CrowdfundingStrings : CodeStrings {
    public string AddProject => "Add Another Project";
    public string AmountMultipleOf => "Amount must be a multiple of";
    public string ApiLoading => "Loading...";
    public string ApiLoadingError => "Unable to load. Please try again.";
    public string ApiLoadingSuccess => "Loaded successfully";
    public string ApiUpdating => "Updating...";
    public string ApiUpdatingError => "Unable to update. Please try again.";
    public string ApiUpdatingSuccess => "Updated successfully";
    public string CampaignGoalOptionsError => "Failed to fetch campaign goal options";
    public string Cancel => "Cancel";
    public string CreateFundraiserError => "Failed to create fundraiser";
    public string CropperGalleryMaximumRequired => "Only %val item(s) are allowed";
    public string CropperGalleryMinimumRequired => "At least %val item(s) are required";
    public string CropperImageCropRequired => "Please edit each image to apply a crop.";
    public string CropperImageLoadError => "Unable to load the image. Please try again.";
    public string CropperImageRequired => "Please first upload image(s).";
    public string CustomAmountDescription => "Custom amount";
    public string EditGoalDescription => "You can modify and/or add projects to your page here.";
    public string EditGoalTitle => "Edit Goal";
    public string GenericError => "Sorry, an error has occurred. Please try again.";
    public string GoalAmountRequired => "Amount is required";
    public string GoalCustomFieldRequired => "%name is Required";
    public string GoalProjectRequired => "Please select the project";
    public string SelectGoal => "Select Goal";
    public string GoalSelectDimension => "Select Dimension";
    public string GoalSelectDimension1 => "Select Dimension 1";
    public string GoalSelectDimension2 => "Select Dimension 2";
    public string GoalSelectDimension3 => "Select Dimension 3";
    public string GoalSelectDimension4 => "Select Dimension 4";
    public string MinimumAmountNote => "Note: minimum amount is";
    public string RaiseGoalAmount => "I hope to raise";
    public string Remove => "Remove";
    public string RichTextEditorNote => "Maximum %val characters";
    public string Save => "Save";
    public string SearchHerePlaceholder => "Type to search...";
    public string SelectDate => "Select date";
    public string SlugFetchError => "Failed to fetch suggestSlug";
    public string SuggestSlugError => "Failed to fetch suggested URL";
    public string TextAreaEditorNote => "Maximum %val characters.";
    public string TextAreaEditorPlaceholder => "Enter text here";
    public string TextAreaEditorTitle => "Text";
    public string TextEditorPlaceholder => "Enter text";
    public string TotalGoalAmountError => "Goals total amount should be at least";
    public string TryAgainError => "Something went wrong. Please try again.";
}