name: Babar

on:
  issue_comment:
    types: [created]

jobs:
  babar:
    if: ${{ startsWith(github.event.comment.body, '/babar ') }}
    uses: n3oltd/actions/.github/workflows/n3o-babar.yml@main
    secrets: inherit
