name: Main CI

on:
  push:
    branches: main
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  myget:
    name: MyGet
    uses: n3oltd/actions/.github/workflows/dotnet-build-pack-push.yml@main
    with:
      dotnet-version: 8.x
      run-pack: true
      version-strategy: date
      nuget-source: https://www.myget.org/F/n3o/api/v2/package
      sentry-project: sites
    secrets:
      nuget-api-key: ${{ secrets.MYGET_API_KEY }}
      sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
