name: v16 CI

on:
  push:
    branches: v-16

  workflow_dispatch:

jobs:
  myget:
    name: MyGet
    uses: n3oltd/actions/.github/workflows/dotnet-build-pack-push.yml@main
    with:
      dotnet-version: 9.x
      run-pack: true
      version-strategy: date
      nuget-source: https://www.myget.org/F/n3o-umbraco/api/v2/package
    secrets:
      nuget-api-key: ${{ secrets.MYGET_API_KEY }}
